### ISSUE TITLE
Question: How to remove the space in between the items?

### ISSUE THREAD

**Issue by Manikkumar1988** [1ud0v1c/CarouselViewPager#1]

**Comment by 1ud0v1c** [comment]
I adapted the method computePadding to handle the space between items but with different scaling, it was actually not the case, explaining why you saw a space between the items. If you update your repository you should be good to go !

By the way, by default there is a padding between items, if you don't want this padding, juste use the method setPaddingBetweenItem() and pass 0 as argument.
